set FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `ui_component`;
DROP TABLE IF EXISTS `template_user_permissions`;
DROP TABLE IF EXISTS `template`;
DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `section_type`;
DROP TABLE IF EXISTS `section`;
DROP TABLE IF EXISTS `object_tags`;
DROP TABLE IF EXISTS `hf_ui_component`;
DROP TABLE IF EXISTS `hf_section`;
DROP TABLE IF EXISTS `hf_permissions`;
DROP TABLE IF EXISTS `form`;
DROP TABLE IF EXISTS `facility_templates`;
DROP TABLE IF EXISTS `doctor_templates`;
DROP TABLE IF EXISTS `data`;
DROP TABLE IF EXISTS `answer`;set FOREIGN_KEY_CHECKS = 1;
